### PR TITLE
update repo

### PR DESCRIPTION
**Pull request by AnfalAnsari**

### CODE REVIEW

**Review by SanjeevKrishnan — CHANGES_REQUESTED** [review]
@AnfalAnsari Changes Required
1. Rename "Images and videos" as "Images and Videos"
2. Rename Video 1 and Video 2. Names should be self-explanatory. 
3. Report has to be improved. Order of sub-headings is wrong. Mentors list is missing. Text has to be justified.
4. In README.md, move Limitations and Future Improvement to last
5. In README.md, team members and mentors' should be an ordered list.Also, hyperlink names with their Github profile link.
6. in README.md, justify the text using HTML tags.

**Comment by AnfalAnsari** [comment]
complete

**Review by SanjeevKrishnan — APPROVED** [review]
@AnfalAnsari Fine Work!
@Shubhanshu07 I suggest for merge!

**Comment by agshubhs** [comment]
@AnfalAnsari Flow chart is not there in Readme.

**Comment by agshubhs** [comment]
@AnfalAnsari Nice work looks good to me.
Merging the PR

**Pull request merged**
